googlemaps/android-maps-ktx

- maps-utils-ktx/build.gradle
Using `api` instead of `implementation` so that consumers can include this library
without needing to also include the AMU library.
> fix: Use api instead of implementation.

- .travis.yml
Executing build task when running the deploy step. I think this is why the auto-deploy when pushing a new tag
is failing (i.e. .aar file cannot be found).
See: https://travis-ci.org/github/googlemaps/android-maps-ktx/builds/661312633
> build: Add build task when deploying.

- build.gradle
- maps-utils-ktx/build.gradle
The dependencies node was missing in the published `pom.xml` in maven central. This PR addresses that by adding it. This was verified working in my test app.
Generated `pom.xml` now looks like:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<modelVersion>4.0.0</modelVersion>
<groupId>com.google.maps.android</groupId>
<artifactId>maps-utils-ktx</artifactId>
<version>0.1.1</version>
<packaging>aar</packaging>
<name>maps-utils-ktx</name>
<description>Kotlin extensions (KTX) for Google Maps SDK</description>
<url>https://github.com/googlemaps/android-maps-ktx</url>
<organization>
<name>Google …
```
> fix: Add dependencies of maps-utils-ktx in pom

- maps-utils-ktx/src/main/java/com/google/maps/android/ktx/LatLng.kt
- maps-utils-ktx/src/test/java/com/google/maps/android/ktx/LatLngTest.kt
`Polygon.kt` already contain these extensions but these should be added to `List<LatLng>` extensions as well.
> feat: Adding PolyUtil extensions to List<LatLng>

- build.gradle
Bump android-maps-utils Java lib to v1.0.2
> chore: Bump android-maps-utils Java lib to v1.0.2

- .github/ktx-docs.yml
Sync `gh-pages` branch whenever a new release is pushed. Will merge this in since workflows need to land on `master` before they can be tested—will address comments in another PR (if any).
> chore: Add ktx-docs GitHub action.

- .github/workflows/ktx-docs.yml
- .github/workflows/test.yml
- README.md
Consolidating CI to GitHub actions. 
Adding unit test workflow—will remove `.travis.yml` once the release workflow is migrated (will PR that next).
> ci: Add unit test workflow

- README.md
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- maps-ktx/src/main/java/com/google/maps/android/ktx/GoogleMap.kt
- maps-ktx/src/main/java/com/google/maps/android/ktx/MapFragment.kt
- maps-ktx/src/main/java/com/google/maps/android/ktx/StreetViewPanoramaFragment.kt
- maps-ktx/src/main/java/com/google/maps/android/ktx/SupportMapFragment.kt
- maps-ktx/src/main/java/com/google/maps/android/ktx/SupportStreetViewPanoramaFragment.kt
- maps-ktx/src/main/java/com/google/maps/android/ktx/model/CameraPosition.kt
- maps-ktx/src/main/java/com/google/maps/android/ktx/model/CircleOptions.kt
- maps-ktx/src/main/java/com/google/maps/android/ktx/model/GroundOverlayOptions.kt
- maps-ktx/src/main/java/com/google/maps/android/ktx/model/MarkerOptions.kt
- maps-ktx/src/main/java/com/google/maps/android/ktx/model/PolygonOptions.kt
- maps-ktx/src/main/java/com/google/maps/android/ktx/model/PolylineOptions.kt
- maps-ktx/src/main/java/com/google/maps/android/ktx/model/StreetViewPanoramaCamera.kt
- maps-ktx/src/main/java/com/google/maps/android/ktx/model/StreetViewPanoramaOrientation.kt
- maps-ktx/src/main/java/com/google/maps/android/ktx/model/TileOverlayOptioms.kt
- maps-ktx/src/test/java/com/google/maps/android/ktx/model/CameraPositionTest.kt
- maps-ktx/src/test/java/com/google/maps/android/ktx/model/CircleOptionsTest.kt
- maps-ktx/src/test/java/com/google/maps/android/ktx/model/GroundOverlayOptionsTest.kt
- maps-ktx/src/test/java/com/google/maps/android/ktx/model/MarkerOptionsTest.kt
- maps-ktx/src/test/java/com/google/maps/android/ktx/model/PolygonOptionsTest.kt
- maps-ktx/src/test/java/com/google/maps/android/ktx/model/PolylineOptionsTest.kt
- maps-ktx/src/test/java/com/google/maps/android/ktx/model/StreetViewPanoramaCameraTest.kt
- maps-ktx/src/test/java/com/google/maps/android/ktx/model/StreetViewPanoramaOrientationTest.kt
- maps-ktx/src/test/java/com/google/maps/android/ktx/model/TileOverlayOptionsTest.kt
- maps-ktx/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
- maps-utils-ktx/src/test/java/com/google/maps/android/ktx/utils/PolygonTest.kt
Adding Kotlin extensions to the Maps SDK for Android. This is the 1st pass after going through these reference docs: https://developers.google.com/maps/documentation/android-sdk/reference
@barbeau this is ready for review. Once merged, we can push this out on maven as a preview.
> feat: Adding KTX to Maps SDK

- maps-utils-ktx/src/main/java/com/google/maps/android/ktx/utils/geojson/GeoJson.kt
This is needed to construct an instance directly from an Android resource ID using named parameters. 
For example, this is how we construct GeoJsonLayers in the demo app (https://github.com/googlemaps/android-maps-ktx/pull/29).
> chore: Add GeoJsonLayer constructor alias for a resource ID

- maps-utils-ktx/src/main/java/com/google/maps/android/ktx/utils/collection/MarkerManager.kt
Adding a helper when adding a new marker to the marker collection. This is similar to the [GoogleMaps.addMarker](https://github.com/googlemaps/android-maps-ktx/blob/master/maps-ktx/src/main/java/com/google/maps/android/ktx/GoogleMap.kt#L77) extension method. 
Something we can add to the demo once merged.
_Before_:
```kotlin
collection.addMarker(
MarkerOptions()
.position(LatLng(51.150000, -0.150032))
.icon(BitmapDescriptorFactory.defaultMarker(BitmapDescriptorFactory.HUE_AZURE))
.title("Unclustered marker")
)
```
_After_:
```kotlin
collection.addMarker {
position(LatLng(51.150000, -0.150032))
icon(BitmapDescriptorFactory.defaultMarker(BitmapDescriptorFactory.HUE_AZURE))
title("Unclustered marker")
}
```
> feat: Add MarkerManager.Collection.addMarker helper

- maps-utils-ktx/src/main/java/com/google/maps/android/ktx/utils/LatLng.kt
- maps-utils-ktx/src/test/java/com/google/maps/android/ktx/utils/LatLngTest.kt
Enable destructuring of LatLng objects.
e.g.
```kotlin
val (lat, lng) = LatLng(1.0, 2.0)
```
> feat: Enable LatLng destructuring.

- README.md
This PR adds setup instructions for the demo app to the README.
@arriolac I tried to add an app screenshot (re-using the screenshot from the [existing AMU docs multi-layer entry](https://developers.google.com/maps/documentation/android-sdk/utility)) to call attention to this section, but adding images in-line in markdown is always a little awkward. IMHO, it's not great, but it's not terrible. LMKWYT - I can remove it if you prefer.
Here's what it currently looks like:
> docs: Add demo app instructions to README

- README.md
- app/src/main/java/com/google/maps/android/ktx/demo/MainActivity.kt
- maps-ktx/src/main/java/com/google/maps/android/ktx/MapFragment.kt
- maps-ktx/src/main/java/com/google/maps/android/ktx/MapsExperimentalFeature.kt
- maps-ktx/src/main/java/com/google/maps/android/ktx/StreetViewPanoramaFragment.kt
- maps-ktx/src/main/java/com/google/maps/android/ktx/SupportMapFragment.kt
- maps-ktx/src/main/java/com/google/maps/android/ktx/SupportStreetViewPanoramaFragment.kt
Removing @MapsExperimentalFeature requirement on suspending functions as coroutines are production ready.
> feat: Remove MapsExperimentalFeature annotation requirement.

- build.gradle
- maps-ktx/src/main/java/com/google/maps/android/ktx/MapView.kt
- maps-ktx/src/main/java/com/google/maps/android/ktx/StreetViewPanoramaView.kt
Adds the following methods:
```
val mapView: MapView = // ...
lifecycle.coroutineScope.launchWhenCreated {
val googleMap = mapView.awaitMap()
}
```
```
val view: StreetViewPanoramaView = // ...
lifecycle.coroutineScope.launchWhenCreated {
val panoramaView = view.awaitStreetViewPanorama()
}
```
Additional changes:
* Bump Kotlin and Utility Library versions
Fixes #70
> feat: Add suspending fun to MapView and StreetViewPanorama

- README.md
- build.gradle
- maps-ktx/build.gradle
- maps-utils-ktx/build.gradle
- maps-utils-v3-ktx/build.gradle
- maps-v3-ktx/build.gradle
Modifying which dependencies are included in the compile scope vs. run-time scope. This is a breaking change.
**Run-time Dependencies**:
You must already have the Kotlin and Coroutine dependencies included in your Gradle file which IMO is an acceptable requirement (i.e. if you're even considering this KTX library, you must already have Kotlin configured in your project). Specifically, these must be defined in your app's `build.gradle` file.
```
dependencies {
implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.72"
implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.3.2"
}
```
**Compile-time Dependencies**
You will have these dependencies included at compile-time but these can still be overridden with a different version by explicitly adding the corresponding …
> feat: Modifying transitive dependencies

- maps-ktx/src/main/java/com/google/maps/android/ktx/GoogleMap.kt
Fixes #80.
- Removed the added listeners in the `awaitClose` within the `GoogleMap.cameraEvents(): Flow<CameraEvent>` implementation.
- Removed the unnecessary `inline` keyword as the function has no parameters of function types.
Also made a couple of unrelated changes (let me know if you want them in a separate PR):
- Also bumped coroutines to version 1.3.8
- changed `kotlin-stdlib-jdk7` to `kotlin-stdlib` as no Java 7 APIs are used.
Ran `./gradlew assemble check` locally.
> fix: Remove listeners in GoogleMap.cameraEvents(): Flow<CameraEvent> implementation

- README.md
Seems the version did not correlate with https://github.com/googlemaps/android-maps-utils release making gradle unable to sync.
> docs: [ Readme ] correct android-maps-utils version

- .releaserc
Updating regexp so that only the ktx lib versions are bumped on a semantic release.
> chore: Update .releaserc README regexp.

- app/src/main/java/com/google/maps/android/ktx/demo/MainActivity.kt
- app/src/main/res/layout/activity_main.xml
- maps-ktx/src/main/java/com/google/maps/android/ktx/GoogleMap.kt
Adding `awaitAnimation()` which allows you to wait for an animation to complete within a coroutine scope. Particularly handy when you need to chain multiple animations together. Previously, you would need to nest a couple of `CancelableCallback`, this feature flattens it. Also updated sample app to demonstrate this.
https://user-images.githubusercontent.com/463186/108136603-3783d700-706f-11eb-884b-47d803438c53.mov\
**Before**
```kotlin
map.animateCamera(animation1, object : GoogleMap.CancelableCallback {
override fun onFinish() {
map.animateCamera(animation2,  object : GoogleMap.CancelableCallback {
override fun onFinish() {
map.animateCamera(animate3,  object : GoogleMap.CancelableCallback {
override fun onFinish() { // ...and so on }
override fun onCancel() { }
})
}
override fun …
```
> feat: Add suspending awaitAnimation()

- .github/workflows/docs.yml
- .github/workflows/publish.yml
Removing `workflow_dispatch` in an attempt to fix #120. Workflows can still be triggered using `repository_dispatch`.
> chore: Remove workflow_dispatch and update create-pull-request to v3.

- .github/workflows/test.yml
- app/src/main/java/com/google/maps/android/ktx/demo/MainActivity.kt
- build.gradle
- maps-ktx/src/main/java/com/google/maps/android/ktx/GoogleMap.kt
Renamed `awaitAnimation` to `awaitAnimateCamera` to match the underlying method name. Not only does this match the original method, but this is also a lot more specific. The former method name could be confusing since it's not clear what is being animated.
BREAKING CHANGE: Renamed `awaitAnimation` to `awaitAnimateCamera`
> fix: Rename awaitAnimation to awaitAnimateCamera

- app/src/main/java/com/google/maps/android/ktx/demo/MainActivity.kt
- maps-ktx/src/main/java/com/google/maps/android/ktx/GoogleMap.kt
Adds camera flow events and deprecates `cameraEvents()`. See #111 for reasoning.
> feat: Add camera specific flow events and deprecate cameraEvents().

- app/build.gradle
- maps-ktx/src/main/AndroidManifest.xml
- maps-utils-ktx/src/main/AndroidManifest.xml
- maps-utils-v3-ktx/src/main/AndroidManifest.xml
- maps-v3-ktx/src/main/AndroidManifest.xml
Builds were presenting a warning when the `maps-utils-ktx` library is used since the manifest package name conflicts with the utility library's package name. This change assigns unique package names to each lib in this repo.
Fixes #135 🦕
> fix: Assign unique package names to libs.

- maps-ktx/src/main/java/com/google/maps/android/ktx/GoogleMap.kt
Add `circleClickEvents()`. Part of #111
> feat: Add circleClickEvents()

- app/build.gradle
- maps-ktx/src/main/java/com/google/maps/android/ktx/GoogleMap.kt
Add indoorStateChangeEvents(). Part of #111
> feat: Add indoorStateChangeEvents()

- app/build.gradle
Update `secrets-gradle-plugin` to v1.1.0
> chore: Update secrets-gradle-plugin to 1.1.0

- app/build.gradle
- maps-ktx/build.gradle
- maps-utils-ktx/build.gradle
- maps-utils-v3-ktx/build.gradle
- maps-v3-ktx/build.gradle
Fix based on recommended fixes from `release` workflow failure: https://github.com/googlemaps/android-maps-ktx/runs/3625368037?check_suite_focus=true
> chore: Set sourceCompatibility and targetCompatibility to 1.8

- app/src/main/java/com/google/maps/android/ktx/demo/MainActivity.kt
- maps-ktx/src/main/java/com/google/maps/android/ktx/GoogleMap.kt
Currently the `reason` parameter from `onCameraMoveStarted (int reason)` method in the `GoogleMap.OnCameraMoveStartedListener` isn't being passed through to the Flow:
https://developers.google.com/android/reference/com/google/android/gms/maps/GoogleMap.OnCameraMoveStartedListener
This PR passes the integer value through to the Flow.
Also add it to the demo app.
Closes #168
---
Fixes #168 🦕
> fix: Add missing reason for cameraMoveStartedEvents() flow

- .github/workflows/release.yml
This PR sets the Java version 17 for the release flow.
> chore: setting Java 17 for the release flow

- .github/workflows/docs.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- app/build.gradle
- build.gradle
- gradle.properties
- maps-ktx/build.gradle
- maps-utils-ktx/build.gradle
Thank you for opening a Pull Request!
---
Fixes https://github.com/googlemaps/android-maps-ktx/issues/266  🦕
> fix: bring back Java 8 compatibility

- .github/lint-report.yml
- app/build.gradle
- maps-ktx/build.gradle
- maps-utils-ktx/build.gradle
The following PR adds a Lint report, generates the SARIF files and upload them to GitHub, so we can get Lint reports on each PR and activate GitHub Code scanning alerts.
> chore: added Lint report

- .github/workflows/dependabot.yml
This PR removes the automerge from android-maps-ktx, which we want to avoid to prevent errors during runtime.
> chore: remove automerge

- gradle/libs.versions.toml
This PR increases the Play Services Map version the android-maps-utils to [19.2.0](https://developers.google.com/android/guides/releases) and the androidMapsUtils to 3.12.0
> feat: increases Play Services Maps version

- .releaserc
This PR fixes a configuration line on the .releaserc flow to change the version after a release has been done (i.e., KTS files must use now " instead of ')
> fix: fixed release config

- .github/workflows/release.yml
- .releaserc
- build-logic/convention/build.gradle.kts
- build-logic/convention/src/main/kotlin/PublishingConventionPlugin.kt
- gradle.properties
- gradle/libs.versions.toml
The following PR migrates from the maven-publish plugin to vanniktech, to support the new Maven Central.
This PR provides the new configuration and data we need (including the maven central username and password)
> chore: migrating to vanniktech plugin

- .github/workflows/docs.yml
This issue fixes the path for the new Dokka plugin.
> build: fix dokka url

- .github/workflows/lint-report.yml
This PR runs the Lint workflow only on PRs.
> chore: run lint only on PR
