CHANGELOG.md
README.md
build.gradle

chore(Release): 0.2

---

CHANGELOG.md
README.md
build.gradle
maps-utils-ktx/build.gradle

Release 0.3. Adding functionality in `./maps-ktx/build.gradle` to release `maps-ktx` as well.

chore(Release): 0.3

---

.github/workflows/docs.yml

Generating `maps-ktx` docs in GitHub workflow.

build: Generating maps-ktx docs

---

README.md

Adding example how awaitMap() could be used.

docs: Adding example for awaitMap()

---

README.md

Noticed in https://github.com/googlemaps/android-maps-ktx/pull/29#discussion_r401819544.

docs: Fix GeoJson alias constructor in README

---

CHANGELOG.md
README.md
build.gradle

chore(Release): 0.3.1

---

index.html

Adding a root `index.html` file so that documentation for both libraries are visible. Will update the README in a separate PR.

docs: Create root index.html

---

README.md

docs: Update README javadoc link

---

build.gradle

feat: Bump AMU version.

---

maps-utils-ktx/src/main/java/com/google/maps/android/ktx/utils/collection/CircleManager.kt
maps-utils-ktx/src/main/java/com/google/maps/android/ktx/utils/collection/GroundOverlayManager.kt
maps-utils-ktx/src/main/java/com/google/maps/android/ktx/utils/collection/PolygonManager.kt
maps-utils-ktx/src/main/java/com/google/maps/android/ktx/utils/collection/PolylineManager.kt

feat: Add model helpers to Manager objects.

feat: Add model helpers to Manager objects.

---

app/src/main/java/com/google/maps/android/ktx/demo/MainActivity.kt

Mirroring changes in https://github.com/googlemaps/android-samples/pull/193

docs: Update demo with optional for Google Map, KTX for markerCollection

---

.github/workflows/docs.yml

build(Docs): Generate docs for maps-utils-v3-ktx

---

app/build.gradle
app/src/main/java/com/google/maps/android/ktx/demo/MainActivity.kt

chore(deps): Bump maps-ktx in demo app to 1.7.0

---

README.md
app/build.gradle
app/src/main/java/com/google/maps/android/ktx/demo/MainActivity.kt
maps-ktx/src/main/java/com/google/maps/android/ktx/GoogleMap.kt

feat: Adding cameraEvents() method to consume camera events using Kotlin Flow

---

.github/workflows/release.yml
.releaserc

Change branch from master to main. See: https://github.com/github/renaming

chore: s/master/main

---

maps-ktx/src/main/java/com/google/maps/android/ktx/GoogleMap.kt

Fix scenario where app can crash due to unhandled exception from invoking offer() on a closed channel.
Fixes #85

fix: Silently catch exception from offer() if channel is closed.

---

README.md

Thank you for opening a Pull Request!
---
Fixes #<issue_number_goes_here> 🦕

chore: Update versions used for V3 SDK

---

maps-ktx/src/main/java/com/google/maps/android/ktx/MapFragment.kt
maps-ktx/src/main/java/com/google/maps/android/ktx/SupportMapFragment.kt

fix: Use suspendCancellationCoroutine instead of suspendCoroutine

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

Update gradle to 6.1.1 and Kotlin to 1.4.0

feat: Update gradle version and Kotlin.

---

.gitignore
README.md
app/.gitignore
app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/com/google/maps/android/ktx/demo/MainActivity.kt
build.gradle
gradle/wrapper/gradle-wrapper.properties
secure.defaults.properties

Using secrets-gradle-plugin to provider GMP API key to sample app.

chore: Using secrets_gradle_plugin

---

app/src/main/java/com/google/maps/android/ktx/demo/MainActivity.kt
app/src/main/res/layout/activity_main.xml
app/src/main/res/values/colors.xml
maps-ktx/src/main/java/com/google/maps/android/ktx/GoogleMap.kt

Added `awaitMapLoad()` and `awaitSnapshot()`. Updated sample app to demonstrate usage.

feat: Adding suspending functions awaitSnapshot and awaitMapLoad.

---

.github/workflows/release.yml

Add parenthesis around sonatype password.

chore: Add parenthesis around sonatype password.

---

maps-ktx/src/main/java/com/google/maps/android/ktx/GoogleMap.kt

Add `groundOverlayClicks()`. Part of #111

feat: Add groundOverlayClicks()

---

maps-ktx/src/main/java/com/google/maps/android/ktx/GoogleMap.kt

feat: Add flow support for info window events. Part of #111

feat: Add flow support for info window events.

---

build.gradle
maps-utils-v3-ktx/build.gradle
maps-v3-ktx/build.gradle

Remove jcenter() as a repo and use mavenCentral().

chore: Remove jcenter.

---

app/build.gradle
app/src/main/java/com/google/maps/android/ktx/demo/MainActivity.kt
build.gradle
maps-ktx/src/main/java/com/google/maps/android/ktx/GoogleMap.kt
maps-ktx/src/main/java/com/google/maps/android/ktx/StreetViewPanoramaView.kt

feat: Add Kotlin Flow extensions for maps-ktx and maps-v3-ktx

---

.github/dependabot.yml
app/build.gradle

Add maps_android_utils_ktx_install_snippet to main branch.

chore: Add maps_android_utils_ktx_install_snippet

---

README.md

Adding deprecation notice for V3 Beta.

docs: Add V3 deprecation notice.

---

build.gradle

Update Maps to 18.0.0 and update minSDK version to match the minSDK of 18.0.0.

feat: Update Maps to 18.0.0

---

.github/blunderbuss.yml

chore: Update blunderbuss.yml file.

---

.github/workflows/docs.yml

The following PR fixes the Dokka command
---
Fixes #220  🦕

fix: fixed Dokka command

---

.github/CODEOWNERS
.github/workflows/docs.yml

chore: update docs.yml

---

gradle/libs.versions.toml

This PR increases the Maps SDK version to 19.0.0

feat: updated to Maps SDK 19.0.0

---

.github/workflows/release.yml

This PR fixes an issue with the config for the Sonatype release.

chore: fixed release config

---

.github/blunderbuss.yml

Thank you for opening a Pull Request!
---
Fixes #<issue_number_goes_here> 🦕

chore: updates default PR assignee to dkhawk
